name: Sync Hagezi Blocklists → Cloudflare

on:
  schedule:
    - cron: "0 2 * * *" # daily 02:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Dry-run (scheduled)
        if: github.event_name == 'schedule'
        env:
          API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          LIST_ID: ${{ secrets.CF_LIST_ID }}
        run: |
          python scripts/sync_cf_blocklist.py --config config/sources.json --dry-run

      - name: Manual push (dispatch) or main-branch push
        if: github.event_name == 'workflow_dispatch' || github.ref == 'refs/heads/main'
        env:
          API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          LIST_ID: ${{ secrets.CF_LIST_ID }}
        run: |
          python scripts/sync_cf_blocklist.py --config config/sources.json